services:
  mysql:
    image: mysql:8.4
    container_name: room-booking-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: room_booking
    ports:
      - "3307:3306"
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: